---
language: python
group: travis_latest
cache: pip
python:
  - 3.8
env:
  global:
    - TOX_TESTENV_PASSENV='TRAVIS TRAVIS_*'
    - TOX_SKIP_MISSING_INTERPRETERS=False
    - COVERALLS_SERVICE_NAME=travis-ci
  jobs:
    - TOXENV=lint
    - TOXENV=security
    - TOXENV=pkg
    - TOXENV=style
jobs:
  include:
    - python: 3.6
      # env: TOXENV=py36-coveralls
      env: TOXENV=py36
    - python: 3.7
      # env: TOXENV=py37-coveralls
      env: TOXENV=py37
    - python: 3.8
      # env: TOXENV=py38-coveralls
      env: TOXENV=py38
    - python: pypy3.6-7.1.1
      env: TOXENV=pypy36
    - python: "nightly"
      env: TOXENV=py3
  allow_failures:
    - python: "nightly"
    - env: TOXENV=security
  fast_finish: true
install: pip3 install 'tox < 3.15'
script:
  - tox
notifications:
  email:
    on_success: change
    on_failure: change  # `always` will be the setting once code changes slow down
